version: '2'

services:
    api:
        image: practicaldevops/api_dev
        environment:
            NODE_ENV: development
        ports:
            - 3002:3000
        volumes:
            - .:/usr/src/api
        command: nodemon .
    mysqlDB:
        image: practicaldevops/mysql_dev
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PWD}"
        ports:
            - 3306:3306
        volumes:
            - ../dev_db/:/var/lib/mysql
